import React from 'react';
import userPhoto from '../assets/images/userPhoto.png';
import confirmIcon from '../assets/Icons/confirmIcon.svg';

export default function loadLists() {
  return [
    {
      title: 'Demandas (5)',
      rearrange: false,
      status: 'demand',
      cards: [
        {
          id: 1,
          labels: ['#33a852'],
          service: 'Requerimento',
          time: 'Prazo:',
          date: '30/03/2023',
          local: 'Local:',
          place: 'São Paulo, SP',
          name: 'José da Silva',
          user: <img src={userPhoto} alt="" />,
          details: 'Ver Detalhes',
          confirmButton: <img src={confirmIcon} alt="" />,
        },
        {
          id: 2,
          labels: ['#33a852'],
          service: 'Requerimento',
          time: 'Prazo:',
          date: '30/03/2023',
          local: 'Local:',
          place: 'São Paulo, SP',
          name: 'José da Silva',
          user: <img src={userPhoto} alt="" />,
          details: 'Ver Detalhes',
          confirmButton: 'icone',
        },
        {
          id: 3,
          labels: ['#33a852'],
          service: 'Requerimento',
          time: 'Prazo:',
          date: '30/03/2023',
          local: 'Local:',
          place: 'São Paulo, SP',
          name: 'José da Silva',
          user: <img src={userPhoto} alt="" />,
          details: 'Ver Detalhes',
          confirmButton: 'icone',
        },
        {
          id: 4,
          labels: ['#33a852'],
          service: 'Requerimento',
          time: 'Prazo:',
          date: '30/03/2023',
          local: 'Local:',
          place: 'São Paulo, SP',
          name: 'José da Silva',
          user: <img src={userPhoto} alt="" />,
          details: 'Ver Detalhes',
          confirmButton: 'icone',
        },
        {
          id: 5,
          labels: ['#33a852'],
          service: 'Requerimento',
          time: 'Prazo:',
          date: '30/03/2023',
          local: 'Local:',
          place: 'São Paulo, SP',
          name: 'José da Silva',
          user: <img src={userPhoto} alt="" />,
          details: 'Ver Detalhes',
          confirmButton: 'icone',
        },
      ],
    },
    {
      title: 'Propostas Enviadas (1)',
      rearrange: true,
      status: 'sent',
      cards: [
        {
          id: 6,
          labels: ['#fabb05'],
          service: 'Requerimento',
          time: 'Prazo:',
          date: '30/03/2023',
          local: 'Local:',
          place: 'São Paulo, SP',
          name: 'José da Silva',
          user: <img src={userPhoto} alt="" />,
          details: 'Ver Detalhes',
          confirmButton: 'icone',
        },
      ],
    },
    {
      title: 'Em negociação (3)',
      rearrange: true,
      status: 'negotiate',
      cards: [
        {
          id: 7,
          labels: ['#e94235'],
          service: 'Requerimento',
          time: 'Prazo:',
          date: '30/03/2023',
          local: 'Local:',
          place: 'São Paulo, SP',
          name: 'José da Silva',
          user: <img src={userPhoto} alt="" />,
          details: 'Ver Detalhes',
          confirmButton: 'icone',
        },
        {
          id: 8,
          labels: ['#e94235'],
          service: 'Requerimento',
          time: 'Prazo:',
          date: '30/03/2023',
          local: 'Local:',
          place: 'São Paulo, SP',
          name: 'José da Silva',
          user: <img src={userPhoto} alt="" />,
          details: 'Ver Detalhes',
          confirmButton: 'icone',
        },
        {
          id: 9,
          labels: ['#e94235'],
          service: 'Requerimento',
          time: 'Prazo:',
          date: '30/03/2023',
          local: 'Local:',
          place: 'São Paulo, SP',
          name: 'José da Silva',
          user: <img src={userPhoto} alt="" />,
          details: 'Ver Detalhes',
          confirmButton: 'icone',
        },
      ],
    },
    {
      title: 'Executando (3)',
      rearrange: true,
      status: 'executing',
      cards: [
        {
          id: 10,
          labels: ['#4285f4'],
          service: 'Requerimento',
          time: 'Prazo:',
          date: '30/03/2023',
          local: 'Local:',
          place: 'São Paulo, SP',
          name: 'José da Silva',
          user: <img src={userPhoto} alt="" />,
          details: 'Ver Detalhes',
          confirmButton: 'icone',
        },
        {
          id: 11,
          labels: ['#4285f4'],
          service: 'Requerimento',
          time: 'Prazo:',
          date: '30/03/2023',
          local: 'Local:',
          place: 'São Paulo, SP',
          name: 'José da Silva',
          user: <img src={userPhoto} alt="" />,
          details: 'Ver Detalhes',
          confirmButton: 'icone',
        },
        {
          id: 12,
          labels: ['#4285f4'],
          service: 'Requerimento',
          time: 'Prazo:',
          date: '30/03/2023',
          local: 'Local:',
          place: 'São Paulo, SP',
          name: 'José da Silva',
          user: <img src={userPhoto} alt="" />,
          details: 'Ver Detalhes',
        },
      ],
    },
  ];
}
